name: Generate M3U8

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (local)
        uses: ./.github/actions/local-checkout
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        shell: bash
        run: |
          set -e
          cd repo
          python3 --version
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Generate playlists
        shell: bash
        env:
          STREAMLINK_PLUGIN_DIR: ${{ github.workspace }}/repo/src/plugins
        run: |
          set -e
          cd repo
          python3 src/generate.py config/config.json

      - name: Commit & push changes
        shell: bash
        run: |
          set -e
          cd repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output
          git diff --cached --quiet || git commit -m "Update m3u8 playlists"
          git push
